version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 812541448385.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=812541448385.dkr.ecr.ap-south-1.amazonaws.com/web_application_python
      - IMAGE_TAG=latest

  build:
    commands:
      - echo Build started
      - echo Building the Docker image...
      - docker build -t web_application_python .
      - docker tag web_application_python:latest 812541448385.dkr.ecr.ap-south-1.amazonaws.com/web_application_python:latest

  post_build:
    commands:
      - echo Build completed
      - echo Pushing the Docker image to ECR...
      - docker push 812541448385.dkr.ecr.ap-south-1.amazonaws.com/web_application_python:latest
      - echo Writing image definitions file...
      - printf '[{"name":"web_application_python","imageUri":"%s"}]' "812541448385.dkr.ecr.ap-south-1.amazonaws.com/web_application_python:latest" > imagedefinitions.json

  files:
    - imagedefinitions.json
